const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const source = fs.readFileSync(process.env.PDF_REVIEW_HTML || path.join(__dirname, '../src/index.template.html'), 'utf8');
function section(start, end) { const a=source.indexOf(start),b=source.indexOf(end,a+start.length); assert(a>=0&&b>a,`${start} / ${end}`); return source.slice(a,b); }
function deferred() { let resolve,reject; const promise=new Promise((yes,no)=>{resolve=yes;reject=no}); return {promise,resolve,reject}; }
function review(comment='A-only review',page=1) { return {id:`review-${page}`,page,type:'note',status:'open',targetType:'text',quote:'Original quote',comment,createdAt:'2026-10-04T00:00:00Z',anchor:{rects:[[1,2,3,4]]}}; }
function harness() {
 const downloads=[],statuses=[],toasts=[],errors=[];
 const state={generation:1,file:{name:'source-A.pdf'},pdfDoc:{},reviews:[review()],reviewSort:'page',exportJob:null,exportBaseName:''};
 const el=()=>({disabled:false,textContent:'',value:'',checked:false,hidden:false,focus(){},select(){},setAttribute(){}});
 const els=Object.fromEntries(['exportFileName','exportHtml','exportMarkdown','exportCsv','includePdf','includeAreaImages','exportTotalCount','exportOpenCount','exportResolvedCount','includeAreaImagesOption','exportStatus'].map(k=>[k,el()]));
 els.exportFileName.value='custom-review'; els.includePdf.checked=true;
 els.exportDialog={open:true,close(){this.open=false},showModal(){this.open=true},setAttribute(){}};
 const ctx=vm.createContext({state,els,Blob,Map,Date,Uint8Array,JSON,Object,console:{warn(){},error(e){errors.push(e)}},requestAnimationFrame:cb=>cb(),document:{querySelector(){return null}},AppToast:{show(s){toasts.push(s)},hide(){}},setStatus(s){statuses.push(s)},downloadBlob(name,blob){downloads.push({name,blob})},StandaloneAssets:{bytesAsync:async()=>new Uint8Array()},collectPdfCMapsBase64:async()=>({}),bytesToBase64:()=>'',fileToBase64:async f=>Buffer.from(f.name).toString('base64')});
 for (const [start,end] of [['const translations=','      const $='],['function t(k)','function formatBytes'],['function reviewTypeLabel','function clamp'],['function sanitizeExportBaseName','async function captureAreaReviewImages'],['function reportScriptJson','async function wrapSelfExtractingReportHtml'],['function buildStandaloneReportHtml','async function exportHtmlReport'],['async function exportHtmlReport','async function exportSessionJson']]) vm.runInContext(section(start,end),ctx);
 vm.runInContext('let language="en";',ctx);
 return {ctx,state,els,downloads,statuses,toasts,errors};
}
function delayImages(h) { const d=deferred(); h.ctx.captureAreaReviewImages=()=>d.promise; return d; }
async function downloadedText(h) { assert.equal(h.downloads.length,1); return h.downloads[0].blob.text(); }
for (const input of ['edited.html','edited.md','edited.csv',' edited.HTML  ','edited.csv.html']) test(`filename strips known export extensions: ${JSON.stringify(input)}`,()=>{ const h=harness(); assert.equal(h.ctx.sanitizeExportBaseName(input),'edited'); });
test('filename sanitizes unsafe characters and falls back when empty',()=>{ const h=harness(); assert.equal(h.ctx.sanitizeExportBaseName(' path/name.html '),'path-name'); assert.equal(h.ctx.sanitizeExportBaseName('... '),'pdf-review'); assert.equal(h.ctx.sanitizeExportBaseName('a\u007fb'),'a-b'); });
test('closing and reopening preserves the edited basename for this source',()=>{ const h=harness(); h.ctx.openExportDialog(); h.els.exportFileName.value='handoff.html'; h.ctx.closeExportDialog(); h.ctx.openExportDialog(); assert.equal(h.els.exportFileName.value,'handoff.html'); });
test('HTML snapshot preserves PDF, review content, anchors, options, language and filename across awaits',async()=>{
 const h=harness(),d=delayImages(h); const p=h.ctx.exportHtmlReport();
 h.state.reviews[0].comment='Changed after start';h.state.reviews[0].anchor.rects[0][0]=999;h.state.reviews.push(review('Late review',2));h.els.exportFileName.value='late-name';h.els.includePdf.checked=false;vm.runInContext('language="ja"',h.ctx);
 d.resolve(new Map());await p;const html=await downloadedText(h);
 assert.equal(h.downloads[0].name,'custom-review.html');assert.match(html,/A-only review/);assert.doesNotMatch(html,/Changed after start|Late review/);assert.match(html,/"rects":\[\[1,2,3,4\]\]/);assert.match(html,/<html lang="en"/);assert.match(html,new RegExp(Buffer.from('source-A.pdf').toString('base64')));
});
test('repeated HTML and competing CSV actions cannot create duplicate downloads',async()=>{ const h=harness(),d=delayImages(h),p=h.ctx.exportHtmlReport(); assert.equal(h.els.exportCsv.disabled,true); assert.equal(h.els.exportMarkdown.disabled,true); await h.ctx.exportHtmlReport();h.ctx.finishExport('csv',h.ctx.buildCsvExport(),'text/csv'); assert.equal(h.downloads.length,0);d.resolve(new Map());await p;assert.equal(h.downloads.length,1);assert.equal(h.els.exportHtml.disabled,false); });
for(const boundary of ['close','cancel','source']) test(`${boundary} rejects pending HTML and all stale success or error UI`,async()=>{
 for(const fail of [false,true]) { const h=harness(),d=delayImages(h),p=h.ctx.exportHtmlReport();
 if(boundary==='source'){h.state.generation++;h.state.file={name:'source-B.pdf'};h.state.reviews=[review('B-only review')];}else h.ctx.closeExportDialog();
 const status=h.statuses.length,toast=h.toasts.length;fail?d.reject(new Error('late failure')):d.resolve(new Map());await p;
 assert.equal(h.downloads.length,0);assert.equal(h.statuses.length,status);assert.equal(h.toasts.length,toast); }
});
test('a stale job cannot re-enable or finish a newer export',async()=>{const h=harness(),a=delayImages(h),old=h.ctx.exportHtmlReport();h.ctx.closeExportDialog();h.ctx.openExportDialog();const b=delayImages(h),fresh=h.ctx.exportHtmlReport();a.resolve(new Map());await old;assert.equal(h.els.exportHtml.disabled,true);assert.equal(h.downloads.length,0);b.resolve(new Map());await fresh;assert.equal(h.downloads.length,1);});
test('source replacement while reading PDF A cannot mix its bytes with PDF B',async()=>{const h=harness(),reading=deferred(),file=deferred();h.ctx.captureAreaReviewImages=async()=>new Map();h.ctx.fileToBase64=source=>{reading.resolve(source);return file.promise};const p=h.ctx.exportHtmlReport();assert.equal((await reading.promise).name,'source-A.pdf');h.state.generation++;h.state.file={name:'source-B.pdf'};h.state.reviews=[review('B-only review')];file.resolve(Buffer.from('source-A.pdf').toString('base64'));await p;assert.equal(h.downloads.length,0);});
test('compression completion after dismissal cannot download',async()=>{const h=harness(),wrapped=deferred(),started=deferred();h.ctx.CompressionStream=function(){};h.ctx.DecompressionStream=function(){};h.ctx.captureAreaReviewImages=async()=>new Map();h.ctx.wrapSelfExtractingReportHtml=html=>{started.resolve();return wrapped.promise};const p=h.ctx.exportHtmlReport();await started.promise;h.ctx.closeExportDialog();wrapped.resolve('late compressed HTML');await p;assert.equal(h.downloads.length,0);});
test('active export failure remains open, localized and retryable',async()=>{const h=harness();h.ctx.captureAreaReviewImages=async()=>{throw Error('synthetic failure')};await h.ctx.exportHtmlReport();assert.equal(h.downloads.length,0);assert.equal(h.els.exportDialog.open,true);assert.equal(h.els.exportHtml.disabled,false);assert.match(h.els.exportStatus.textContent,/report|export/i);h.ctx.captureAreaReviewImages=async()=>new Map();await h.ctx.exportHtmlReport();assert.equal(h.downloads.length,1);});
test('failed compression still downloads a valid uncompressed report',async()=>{const h=harness();h.ctx.CompressionStream=function(){};h.ctx.DecompressionStream=function(){};h.ctx.captureAreaReviewImages=async()=>new Map();h.ctx.wrapSelfExtractingReportHtml=async()=>{throw Error('no compression')};await h.ctx.exportHtmlReport();assert.match(await downloadedText(h),/<!doctype html>/);});
test('CSV preserves seven columns, BOM, CRLF and all eleven values without formula rewriting',()=>{
 const h=harness(),values=['plain 日本語','comma, quote " here','first\nsecond','first\rsecond','first\r\nsecond','=1+1','+1+1','-1+1','@SUM(1,1)','\t=1+1',' leading and trailing '];h.state.reviews=values.map((v,i)=>({...review(v,i+1),quote:v}));const csv=h.ctx.buildCsvExport();assert.equal(csv.charCodeAt(0),0xfeff);assert.match(csv,/\r\n$/);
 const rows=[];let row=[],field='',quoted=false;for(let i=1;i<csv.length;i++){const c=csv[i];if(quoted){if(c==='"'&&csv[i+1]==='"'){field+='"';i++}else if(c==='"')quoted=false;else field+=c}else if(c==='"')quoted=true;else if(c===','){row.push(field);field=''}else if(c==='\r'&&csv[i+1]==='\n'){row.push(field);rows.push(row);row=[];field='';i++}else field+=c}assert.equal(rows.length,12);assert.deepEqual(rows[0],['Page','Type','Status','Target','Quote','Comment','Created']);for(let i=0;i<values.length;i++){assert.equal(rows[i+1].length,7);assert.equal(rows[i+1][4],values[i]);assert.equal(rows[i+1][5],values[i]);}
});
test('export cancellation is wired for close, Escape, backdrop and source replacement',()=>{assert.match(source,/function closeExportDialog\(/);assert.match(source,/els\.closeExport\.addEventListener\('click',closeExportDialog\)/);assert.match(source,/els\.exportDialog\.addEventListener\('cancel',[^\n]*closeExportDialog/);assert.match(source,/els\.exportDialog\.addEventListener\('click',[^\n]*closeExportDialog/);assert.match(section('async function beginSourceChange','async function openPdf'),/cancelReportExport/);});
test('actual source boundary cancels work, resets filename/options and permits a new source export',async()=>{
 const h=harness(),d=delayImages(h),p=h.ctx.exportHtmlReport();Object.assign(h.ctx,{clearTimeout(){},hideSelectionToolbar(){},clearTextSelection(){},async disposeDocument(){},renderReviewList(){},syncFilterUI(){},updateAreaModeUI(){},updateSessionStatus(){}});vm.runInContext(section('async function beginSourceChange','async function ensurePdfJs'),h.ctx);await h.ctx.beginSourceChange();assert.equal(h.state.exportBaseName,'');assert.equal(h.state.exportJob,null);assert.equal(h.els.exportDialog.open,false);assert.equal(h.els.exportHtml.disabled,false);h.state.file={name:'source-B.pdf'};h.state.reviews=[review('B-only review')];h.ctx.openExportDialog();assert.equal(h.els.exportFileName.value,'source-B-review');d.resolve(new Map());await p;assert.equal(h.downloads.length,0);
 h.ctx.captureAreaReviewImages=async()=>new Map();await h.ctx.exportHtmlReport();assert.match(await downloadedText(h),/B-only review/);
});
test('asset loading cannot commit an export after its dialog closes',async()=>{const h=harness(),assets=deferred(),started=deferred();h.ctx.captureAreaReviewImages=async()=>new Map();h.ctx.StandaloneAssets.bytesAsync=()=>{started.resolve();return assets.promise};const p=h.ctx.exportHtmlReport();await started.promise;h.ctx.closeExportDialog();assets.resolve(new Uint8Array());await p;assert.equal(h.downloads.length,0);});
test('PDF exclusion and language labels remain captured when options change during generation',async()=>{const h=harness(),d=delayImages(h);vm.runInContext('language="ja"',h.ctx);h.els.includePdf.checked=false;const p=h.ctx.exportHtmlReport();h.els.includePdf.checked=true;vm.runInContext('language="en"',h.ctx);d.resolve(new Map());await p;const html=await downloadedText(h);assert.match(html,/<html lang="ja"/);assert.match(html,/メモ/);assert.doesNotMatch(html,/id="embeddedPdfData"/);});
test('area crops use captured PDF and rectangles, cancel the owned render and free canvases',async()=>{
 const h=harness(),render=deferred(),started=deferred(),canvases=[];let cancelled=0;h.state.reviews[0].targetType='area';h.els.includeAreaImages.checked=true;h.els.includePdf.checked=false;
 h.ctx.document.createElement=tag=>{assert.equal(tag,'canvas');const canvas={width:0,height:0,getContext(){return {drawImage(){}}},toDataURL(){return 'data:image/jpeg;base64,synthetic'}};canvases.push(canvas);return canvas};h.ctx.clamp=(n,a,b)=>Math.min(b,Math.max(a,n));h.ctx.pdfPointToViewport=(v,x,y)=>[x,y];h.state.pdfDoc={getPage:async()=>({getViewport:()=>({width:100,height:100}),render(){started.resolve();return {promise:render.promise,cancel(){cancelled++;render.reject(Error('cancelled'))}}}})};
 vm.runInContext(section('async function captureAreaReviewImages','function fileToBase64'),h.ctx);const p=h.ctx.exportHtmlReport();await started.promise;h.ctx.closeExportDialog();await p;assert.equal(cancelled,1);assert.equal(h.downloads.length,0);assert.equal(canvases[0].width,1);assert.equal(canvases[0].height,1);
});
test('area getPage completion after cancellation cannot start a render',async()=>{const h=harness(),page=deferred(),started=deferred();let rendered=0;h.state.reviews[0].targetType='area';h.els.includeAreaImages.checked=true;h.state.pdfDoc={getPage(){started.resolve();return page.promise}};vm.runInContext(section('async function captureAreaReviewImages','function fileToBase64'),h.ctx);const p=h.ctx.exportHtmlReport();await started.promise;h.ctx.closeExportDialog();page.resolve({getViewport(){rendered++;return {width:1,height:1}}});await p;assert.equal(rendered,0);assert.equal(h.downloads.length,0);});
test('all inline application scripts parse in each checked artifact',()=>{for(const match of source.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/g)){if(/type="(?:application\/json|application\/octet-stream)"/.test(match[1]))continue;new vm.Script(match[2]);}});

function realAreaHarness(){const h=harness(),canvases=[],renders=[];h.els.includeAreaImages.checked=true;h.state.reviews[0].targetType='area';h.state.reviews[0].anchor.rects=[[1,2,30,40]];h.ctx.pdfPointToViewport=(vp,x,y)=>[x,y];h.ctx.clamp=(n,min,max)=>Math.min(max,Math.max(min,n));h.ctx.document.createElement=()=>{const c={width:0,height:0,getContext(){return {drawImage(){}}},toDataURL(){return 'data:image/jpeg;base64,TEST'}};canvases.push(c);return c};const page={getViewport(){return {width:100,height:100}},render(){const d=deferred(),task={promise:d.promise,cancel(){d.reject(Object.assign(new Error('cancelled'),{name:'RenderingCancelledException'}))}};renders.push({d,task});return task}};h.state.pdfDoc={getPage:async()=>page};vm.runInContext(section('async function captureAreaReviewImages','function fileToBase64'),h.ctx);return {...h,canvases,renders};}
test('real area render cancel aborts task, clears canvas and prevents download',async()=>{const h=realAreaHarness();const p=h.ctx.exportHtmlReport();await new Promise(setImmediate);assert.equal(h.renders.length,1);assert.equal(h.canvases[0].width,100);h.ctx.closeExportDialog();await p;assert.equal(h.downloads.length,0);assert.equal(h.canvases[0].width,1);assert.equal(h.state.exportJob,null);assert.equal(h.els.exportHtml.disabled,false)});
test('real area render rejection clears canvas and supports retry',async()=>{const h=realAreaHarness();const p=h.ctx.exportHtmlReport();await new Promise(setImmediate);h.renders[0].d.reject(new Error('synthetic render error'));await p;assert.equal(h.canvases[0].width,1);assert.equal(h.els.exportHtml.disabled,false);const retry=h.ctx.exportHtmlReport();await new Promise(setImmediate);h.renders[1].d.resolve();await retry;assert.equal(h.downloads.length,1);assert.ok(h.canvases.every(c=>c.width===1&&c.height===1));assert.match(await h.downloads[0].blob.text(),/data:image\/jpeg;base64,TEST/)});
test('real area crop failure clears page and crop canvas without downloading partial report',async()=>{const h=realAreaHarness();const create=h.ctx.document.createElement;h.ctx.document.createElement=()=>{const c=create();c.toDataURL=()=>{throw new Error('synthetic crop error')};return c};const p=h.ctx.exportHtmlReport();await new Promise(setImmediate);h.renders[0].d.resolve();await p;assert.equal(h.downloads.length,0);assert.ok(h.canvases.every(c=>c.width===1&&c.height===1));assert.match(h.els.exportStatus.textContent,/Could not export/)});
test('HTML malicious-looking comments, quotes and ids remain inert escaped data',async()=>{const h=harness();h.ctx.captureAreaReviewImages=async()=>new Map();const x='</script><script>alert(1)</script><img src=x onerror=alert(2)> & "';Object.assign(h.state.reviews[0],{id:x,comment:x,quote:x});h.state.file={name:x+'.pdf'};await h.ctx.exportHtmlReport();const html=await downloadedText(h);assert.doesNotMatch(html,/<script>alert\(1\)<\/script>/);assert.doesNotMatch(html,/<img src=x/);assert.match(html,/&lt;script&gt;alert\(1\)&lt;\/script&gt;/);assert.match(html,/\\u003c\/script\\u003e/)});
for(const lang of ['ja','en'])test('real failure and cancellation are localized: '+lang,async()=>{const h=harness();vm.runInContext('language='+JSON.stringify(lang),h.ctx);h.ctx.captureAreaReviewImages=async()=>{throw new Error('error')};await h.ctx.exportHtmlReport();assert.equal(h.els.exportStatus.textContent,h.ctx.t('reportFailed'));const d=delayImages(h),p=h.ctx.exportHtmlReport();h.ctx.closeExportDialog();assert.equal(h.els.exportStatus.textContent,h.ctx.t('reportCancelled'));d.resolve(new Map());await p});
test('real FileReader is abortable and clears its reference',async()=>{const h=harness();let reader;class FakeFileReader{constructor(){reader=this}readAsDataURL(){}abort(){this.onabort();this.onloadend()}}h.ctx.FileReader=FakeFileReader;vm.runInContext(section('function fileToBase64','function bytesToBase64'),h.ctx);h.ctx.captureAreaReviewImages=async()=>new Map();const p=h.ctx.exportHtmlReport();await new Promise(setImmediate);assert.ok(h.state.exportJob.reader);h.ctx.closeExportDialog();await p;assert.equal(h.downloads.length,0);assert.equal(h.errors.length,0)});
