const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const source=fs.readFileSync(process.env.PDF_REVIEW_HTML||path.join(__dirname,'../src/index.template.html'),'utf8');
function section(a,b){const x=source.indexOf(a),y=source.indexOf(b,x+a.length);assert(x>=0&&y>x,a);return source.slice(x,y)}
function fn(name){const at=source.lastIndexOf(`function ${name}(`);if(at<0)return '';const a=source.slice(Math.max(0,at-6),at)==='async '?at-6:at;let open=source.indexOf('){',at)+1,depth=1,end=open+1;for(;depth&&end<source.length;end++){if(source[end]==='{')depth++;if(source[end]==='}')depth--;}return source.slice(a,end)}
function deferred(){let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return {promise,resolve,reject}}
function review(id,page=1,status='open',type='note',created=page){return {id,page,status,type,targetType:'text',quote:'quote '+id,comment:'comment '+id,anchor:{rects:[[1,2,3,4]]},createdAt:`2026-10-05T00:00:0${created}Z`,updatedAt:'2026-10-05T00:00:00Z'}}
function element(){const attrs={},events={};return {children:[],attrs,events,value:'',textContent:'',hidden:false,disabled:false,open:false,style:{setProperty(){}},dataset:{},className:'',classList:{add(){},remove(){},toggle(){}},append(...xs){this.children.push(...xs)},replaceChildren(...xs){this.children=xs},setAttribute(k,v){attrs[k]=v},addEventListener(k,v){events[k]=v},close(){this.open=false},showModal(){this.open=true},focus(){},getContext(){return {clearRect(){}}},querySelector(){return null}}}
function harness(){const actions=[],events={},frames=[],calls={renders:0,scrolls:0,saves:0,errors:[],toastHides:0};const els=new Proxy({}, {get(o,k){return o[k]||(o[k]=element())}});const state={phase:'ready',generation:1,file:{name:'A.pdf'},sessionKey:'A',reviews:[review('a'),review('b',2),review('c',3,'resolved')],activeReviewId:'a',currentPage:1,pageCount:3,pdfDoc:{},pageRenderRequest:null,reviewFilterStatus:'all',reviewFilterType:'all',reviewSort:'page',zoomMode:'fit-width',viewport:{scale:1,convertToViewportPoint:(x,y)=>[x,y]}};const document={createElement:element,querySelector:sel=>sel==='dialog[open]'&&Object.values(els).find(e=>e.open)||null};
const context=vm.createContext({state,els,document,Date,Math,Number,String,JSON,clearTimeout,setTimeout,requestAnimationFrame:f=>frames.push(f),crypto:{randomUUID:()=> 'new-id'},window:{addEventListener:(k,v)=>events[k]=v,getSelection:()=>null},t:x=>({matchingReviewPosition:'Review {current} of {count}',matchingReviewCount:'{count} matching reviews'}[x]||x),fmt:(x,values)=>x.replace(/\{(\w+)\}/g,(_,k)=>values[k]),AppToast:{show:(message,opts)=>{if(opts?.onAction)actions.push(opts.onAction)},hide(){calls.toastHides++}},setStatus(){},scheduleAutosave(){calls.saves++},scrollActiveHighlightIntoView(){calls.scrolls++},renderCurrentPage:async()=>{calls.renders++},cancelReportExport(){},hideSelectionToolbar(){state.pendingSelection=null},clearTextSelection(){},disposeDocument:async()=>{state.pdfDoc=null;state.viewport=null},syncFilterUI(){},updateAreaModeUI(){},updateSessionStatus(){},updateExportDialog(){},setMobileView:v=>state.mobileView=v,showError:(message,error)=>calls.errors.push(error.message),isCurrent:g=>g===state.generation,toggleAreaMode:()=>{state.areaMode=!state.areaMode},cancelShiftAreaReview(){},updateReviewDialogMode(){},syncReviewSubmitState(){},reviewQuoteText:r=>r.quote,reviewTypeLabel:x=>x,reviewStatusLabel:x=>x,normalizeReview:r=>r,clamp:(v,a,b)=>Math.max(a,Math.min(b,v)),calculateScale:()=>1});
for(const name of ['getOrderedReviews','getFilteredReviews','updateReviewNavigation','setActiveReview','navigateReview','isViewerShortcutBlocked','renderReviewList','updateToolbar','goToPage','deleteReview','focusReview','toggleReviewStatus','applySessionRecord','restoreSavedSession','beginSourceChange','openReviewDialog','editReview','closeReviewDialog','submitReviewDialog','hideSelectionToolbar','pdfPointToViewport','renderReviewHighlights']){const code=fn(name);if(code)vm.runInContext(code,context)}
return {context,state,els,document,calls,actions,events,frames,loadRender(){vm.runInContext(section('async function renderCurrentPage(','function updateToolbar('),context)},loadKeys(){vm.runInContext(section("window.addEventListener('keydown',e=>{if(e.key==='Shift'","window.addEventListener('keyup'"),context)}}}
const ids=h=>Array.from(h.state.reviews,r=>r.id);
const activeCards=h=>h.els.reviewList.children.filter(c=>c.className.includes('is-active')).length;
function key(h,target,extras={}){let prevented=false;h.events.keydown({key:'PageDown',target,preventDefault(){prevented=true},...extras});return prevented}
function target(tag){return {isContentEditable:false,matches:s=>s.split(',').includes(tag),closest:s=>s.split(',').includes(tag)?{}:null}}
function page(){return {getViewport:()=>({width:100,height:200,scale:1,convertToViewportPoint:(x,y)=>[x,y]}),render:()=>({promise:Promise.resolve(),cancel(){}}),getTextContent:async()=>({items:[]})}}
function completePdf(h){h.state.pdfDoc={getPage:async()=>page()};h.state.pdfjs={TextLayer:class{async render(){} cancel(){}}};h.loadRender()}

test('old Delete Undo cannot insert an A review after source replacement begins',async()=>{const h=harness();h.context.deleteReview('a');await h.context.beginSourceChange();h.actions[0]();assert.deepEqual(ids(h),[]);assert.equal(h.calls.toastHides,1)});
test('same-workspace Undo preserves exact review fields and original order, and is single use',()=>{const h=harness(),before=JSON.stringify(h.state.reviews);h.context.deleteReview('b');h.actions[0]();assert.equal(JSON.stringify(h.state.reviews),before);h.actions[0]();assert.equal(JSON.stringify(h.state.reviews),before)});
test('Undo cannot cross session import/replacement in the same PDF',()=>{const h=harness();h.context.deleteReview('a');h.context.applySessionRecord({reviews:[review('imported',2)]});h.actions[0]();assert.deepEqual(ids(h),['imported'])});
test('clamped and invalid same-page input always shows the true page without rerender',async()=>{for(const raw of ['99','','nope']){const h=harness();h.state.currentPage=3;h.els.pageInput.value=raw;await h.context.goToPage(raw);assert.equal(h.els.pageInput.value,'3',raw);assert.equal(h.calls.renders,0)}const h=harness();h.els.pageInput.value='0';await h.context.goToPage('0');assert.equal(h.els.pageInput.value,'1');assert.equal(h.calls.renders,0)});
test('manual page change clears active review card and highlight together',async()=>{const h=harness();h.context.renderReviewList();assert.equal(activeCards(h),1);await h.context.goToPage(2);assert.equal(h.state.activeReviewId,'');assert.equal(activeCards(h),0);assert.equal(h.els.reviewOverlay.children.some(c=>c.className.includes('is-active')),false)});
test('old source getPage rejection cannot show an error or finish newer loading',async()=>{const h=harness(),d=deferred();h.loadRender();h.state.pdfDoc={getPage:()=>d.promise};const pending=h.context.renderCurrentPage();h.state.generation++;h.state.pdfDoc={};h.els.pageLoading.hidden=false;d.reject(new Error('old A'));await pending;assert.deepEqual(h.calls.errors,[]);assert.equal(h.els.pageLoading.hidden,false)});
test('same-page newer render owns both failures and loading indicator',async()=>{const h=harness(),a=deferred(),b=deferred();h.loadRender();let calls=0;h.state.pdfDoc={getPage:()=>++calls===1?a.promise:b.promise};const first=h.context.renderCurrentPage(),second=h.context.renderCurrentPage();a.reject(new Error('old page'));await first;assert.deepEqual(h.calls.errors,[]);assert.equal(h.els.pageLoading.hidden,false);b.reject(new Error('current page'));await second;assert.deepEqual(h.calls.errors,['current page']);assert.equal(h.els.pageLoading.hidden,true)});
test('normal viewer PageDown works but select/composition/prevented/modal keys are untouched',()=>{for(const [node,extras,modal] of [[target('select'),{},false],[target('div'),{isComposing:true},false],[target('div'),{defaultPrevented:true},false],[target('div'),{},true],[{...target('div'),isContentEditable:true},{},false]]){const h=harness();h.loadKeys();h.els.reviewDialog.open=modal;assert.equal(key(h,node,extras),false);assert.equal(h.state.currentPage,1)}const h=harness();h.loadKeys();assert.equal(key(h,target('div')),true);assert.equal(h.state.currentPage,2)});

test('matching navigation follows composed filters and Page order without changing source order',async()=>{const h=harness();h.state.reviews=[review('third',3,'open','question',1),review('excluded',1,'resolved','question',2),review('first',1,'open','question',3),review('other-type',2,'open','note',4)];h.state.activeReviewId='';h.state.reviewFilterStatus='open';h.state.reviewFilterType='question';h.context.renderReviewList();assert.equal(h.els.prevReview.disabled,true);assert.equal(h.els.reviewPosition.textContent,'2 matching reviews');await h.context.navigateReview(1);assert.equal(h.state.activeReviewId,'first');assert.equal(h.els.reviewPosition.textContent,'Review 1 of 2');await h.context.navigateReview(1);assert.equal(h.state.activeReviewId,'third');assert.equal(h.els.nextReview.disabled,true);assert.equal(h.state.mobileView,'pdf');assert.deepEqual(ids(h),['third','excluded','first','other-type']);assert.equal(h.state.reviewFilterType,'question')});
test('Added order and rapid navigation reach each match once without wrapping',async()=>{const h=harness();h.state.reviews=[review('later',1,'open','note',3),review('earliest',3,'open','note',1),review('middle',2,'open','note',2)];h.state.reviewSort='created';h.state.activeReviewId='';await Promise.all([h.context.navigateReview(1),h.context.navigateReview(1),h.context.navigateReview(1),h.context.navigateReview(1)]);assert.equal(h.state.activeReviewId,'later');assert.equal(h.els.nextReview.disabled,true);await h.context.navigateReview(-1);await h.context.navigateReview(-1);await h.context.navigateReview(-1);assert.equal(h.state.activeReviewId,'earliest');assert.equal(h.els.prevReview.disabled,true)});
test('empty matches and hidden/deleted active match have honest count and first-entry behavior',async()=>{const h=harness();h.state.reviewFilterType='question';h.context.renderReviewList();assert.equal(h.els.prevReview.disabled,true);assert.equal(h.els.nextReview.disabled,true);assert.equal(h.els.reviewPosition.textContent,'0 matching reviews');await h.context.navigateReview(1);assert.equal(h.state.activeReviewId,'a');h.state.reviewFilterType='all';h.state.reviewFilterStatus='resolved';h.context.renderReviewList();assert.equal(h.els.reviewPosition.textContent,'1 matching reviews');await h.context.navigateReview(-1);assert.equal(h.state.activeReviewId,'a');await h.context.navigateReview(1);assert.equal(h.state.activeReviewId,'c');h.context.deleteReview('c');assert.equal(h.els.reviewPosition.textContent,'0 matching reviews')});
test('resolve, edit, delete, Undo and filter/order changes immediately recompute navigation',async()=>{const h=harness();h.state.reviewFilterStatus='open';await h.context.focusReview('a');h.context.toggleReviewStatus('a');assert.equal(h.els.reviewPosition.textContent,'1 matching reviews');await h.context.navigateReview(1);assert.equal(h.state.activeReviewId,'b');h.context.deleteReview('b');assert.equal(h.els.nextReview.disabled,true);h.actions[0]();assert.equal(h.els.reviewPosition.textContent,'Review 1 of 1');h.state.reviewFilterType='note';h.context.editReview('b');h.els.reviewTypeSelect.value='question';h.els.reviewComment.value='revised';h.context.submitReviewDialog();assert.equal(h.els.reviewPosition.textContent,'0 matching reviews');h.state.reviewFilterType='all';h.state.reviewSort='created';h.context.renderReviewList();assert.equal(h.els.reviewPosition.textContent,'Review 1 of 1')});
test('captured text/area and edit drafts survive navigation attempts and a viewport rerender',async()=>{for(const mode of ['text','area','edit']){const h=harness();if(mode==='edit')h.context.editReview('a');else {h.state.pendingSelection={page:1,quote:'captured',rects:[[1,2,3,4]],targetType:mode};h.context.openReviewDialog('question')}h.els.reviewComment.value='unsaved draft';const selection=JSON.stringify(h.state.pendingSelection);await h.context.focusReview('b');await h.context.goToPage(2);await h.context.navigateReview(1);completePdf(h);await h.context.renderCurrentPage();assert.equal(h.state.currentPage,1);assert.equal(h.state.activeReviewId,'a');assert.equal(h.els.reviewComment.value,'unsaved draft');assert.equal(JSON.stringify(h.state.pendingSelection),selection);h.context.closeReviewDialog();await h.context.navigateReview(1);assert.equal(h.state.activeReviewId,'b')}});
test('loading, error, and missing document disable review navigation',async()=>{for(const phase of ['empty','loading','error']){const h=harness();h.state.phase=phase;h.context.renderReviewList();assert.equal(h.els.prevReview.disabled,true);assert.equal(h.els.nextReview.disabled,true);await h.context.navigateReview(1);assert.equal(h.state.activeReviewId,'a')}const h=harness();h.state.pdfDoc=null;h.context.renderReviewList();assert.equal(h.els.nextReview.disabled,true)});
test('source reset clears current marker and session load starts unselected',async()=>{const h=harness();await h.context.beginSourceChange();assert.equal(h.els.reviewPosition.textContent,'0 matching reviews');assert.equal(h.els.nextReview.disabled,true);h.state.file={name:'B.pdf'};h.state.pdfDoc={};h.state.pageCount=3;h.context.applySessionRecord({reviews:[review('restored',2)]});assert.equal(h.els.reviewPosition.textContent,'1 matching reviews');await h.context.navigateReview(1);assert.equal(h.state.activeReviewId,'restored')});
test('viewer review controls, count and help are localized and next to the preview',()=>{const viewer=section('<section class="viewer-pane"','<aside class="review-pane"');assert.match(viewer,/id="previousReviewButton"/);assert.match(viewer,/id="nextReviewButton"/);assert.match(viewer,/id="reviewPosition"[^>]*aria-live="polite"/);for(const key of ['previousReview','nextReview','matchingReviewPosition','matchingReviewCount','helpReviewNavigation'])assert.equal((section('const translations={','const $=').match(new RegExp(key+":",'g'))||[]).length,2,key);assert.match(section('<!-- APP:HELP:BEGIN -->','<!-- APP:HELP:END -->'),/data-i18n="helpReviewNavigation"/)});

test('stale same-page success cannot create a canvas/text task or change newer viewport',async()=>{const h=harness(),a=deferred(),b=deferred();h.loadRender();let calls=0,staleRenders=0;h.state.pdfDoc={getPage:()=>++calls===1?a.promise:b.promise};const first=h.context.renderCurrentPage(),second=h.context.renderCurrentPage(),viewport=h.state.viewport;a.resolve({...page(),render(){staleRenders++;return {promise:Promise.resolve()}}});await first;assert.equal(staleRenders,0);assert.equal(h.state.viewport,viewport);assert.equal(h.els.pageLoading.hidden,false);b.reject(new Error('current'));await second});
for(const stage of ['render','text-content','text-layer'])test(`stale ${stage} rejection is inert after a newer render starts`,async()=>{const h=harness(),old=deferred(),newer=deferred();completePdf(h);let calls=0;const oldPage=page();if(stage==='render')oldPage.render=()=>({promise:old.promise,cancel(){}});if(stage==='text-content')oldPage.getTextContent=()=>old.promise;if(stage==='text-layer')h.state.pdfjs.TextLayer=class{render(){return old.promise}cancel(){}};h.state.pdfDoc.getPage=()=>++calls===1?Promise.resolve(oldPage):newer.promise;const first=h.context.renderCurrentPage();await new Promise(setImmediate);assert.deepEqual(h.calls.errors,[]);const second=h.context.renderCurrentPage();old.reject(new Error('stale '+stage));await first;assert.deepEqual(h.calls.errors,[]);assert.equal(h.els.pageLoading.hidden,false);newer.reject(new Error('newest'));await second;assert.deepEqual(h.calls.errors,['newest'])});
test('rapid same-page focus and manual navigation use only the current active anchor',async()=>{const h=harness();h.state.reviews=[review('a'),review('b')];completePdf(h);await h.context.focusReview('a');await h.context.focusReview('b');await h.context.renderCurrentPage(h.state.generation,{focusReviewId:'a'});assert.deepEqual(h.els.reviewOverlay.children.filter(c=>c.className.includes('is-active')).map(c=>c.dataset.reviewId),['b']);await h.context.goToPage(1);assert.equal(activeCards(h),0);assert.equal(h.els.reviewPosition.textContent,'2 matching reviews');for(const frame of h.frames)frame();assert.equal(h.els.reviewOverlay.children.some(c=>c.className.includes('is-active')),false)});
test('navigation after dialog cancellation works, and source replacement clears obsolete drafts',async()=>{const h=harness();h.state.pendingSelection={page:1,quote:'draft',rects:[[1,2,3,4]]};h.context.openReviewDialog('note');assert.equal(h.els.nextReview.disabled,true);h.context.closeReviewDialog();assert.equal(h.els.nextReview.disabled,false);await h.context.navigateReview(1);assert.equal(h.state.activeReviewId,'b');h.context.editReview('b');await h.context.beginSourceChange();assert.equal(h.els.reviewDialog.open,false);assert.equal(h.state.pendingSelection,null);assert.equal(h.state.editingReviewId,'');assert.equal(h.els.nextReview.disabled,true)});
test('captured area coordinates and comment can still be saved after a viewport rerender',async()=>{const h=harness();h.state.pendingSelection={page:1,targetType:'area',quote:'area',rects:[[11,22,33,44]]};h.context.openReviewDialog('question');h.els.reviewComment.value='keep this comment';completePdf(h);await h.context.renderCurrentPage();h.context.submitReviewDialog();const added=h.state.reviews.at(-1);assert.equal(added.targetType,'area');assert.equal(added.comment,'keep this comment');assert.equal(added.type,'question');assert.deepEqual(Array.from(added.anchor.rects[0]),[11,22,33,44])});
test('navigation leaves anchors, timestamps, comments, and Markdown/CSV export scope unchanged',async()=>{const h=harness(),before=JSON.stringify(h.state.reviews);h.state.reviewFilterStatus='resolved';await h.context.navigateReview(1);assert.equal(JSON.stringify(h.state.reviews),before);vm.runInContext(section('function exportReviewsInPageOrder(','function escapeHtml('),h.context);const csv=h.context.buildCsvExport(),md=h.context.buildMarkdownExport();for(const id of ['a','b','c']){assert.match(csv,new RegExp('comment '+id));assert.match(md,new RegExp('comment '+id))}assert.ok(csv.startsWith('\ufeff'));assert.ok(csv.endsWith('\r\n'))});
test('all native and custom interactive key targets preserve their own interaction',()=>{for(const tag of ['input','textarea','select','button','a','[role="button"]','[role="combobox"]','[role="listbox"]','[role="dialog"]','[contenteditable]']){const h=harness();h.loadKeys();assert.equal(key(h,target(tag)),false,tag);assert.equal(h.state.currentPage,1)}for(const extras of [{isComposing:true},{keyCode:229},{defaultPrevented:true}]){const h=harness();h.loadKeys();assert.equal(key(h,target('div'),extras),false)}});
test('actual Japanese and English navigation labels and counts are used',()=>{for(const language of ['ja','en']){const h=harness();vm.runInContext(section('const translations={','const $=')+`\nlet language='${language}';\n`+fn('t')+fn('fmt'),h.context);h.state.activeReviewId='';h.context.updateReviewNavigation();assert.equal(h.els.reviewPosition.textContent,language==='ja'?'該当 3 件':'Matching reviews: 3');h.context.setActiveReview('b');assert.equal(h.els.reviewPosition.textContent,language==='ja'?'レビュー 2 / 3':'Review 2 of 3');assert.match(source,/els\.prevReview\.addEventListener\('click',\(\)=>void navigateReview\(-1\)\)/);assert.match(source,/els\.nextReview\.addEventListener\('click',\(\)=>void navigateReview\(1\)\)/)}});
test('rapid review navigation on a still-rendering page scrolls the latest anchor after layout',async()=>{const h=harness(),pending=deferred();h.state.reviews=[review('start'),review('a',2),review('b',2)];h.state.activeReviewId='start';completePdf(h);h.state.pdfDoc.getPage=()=>pending.promise;const first=h.context.navigateReview(1);await h.context.navigateReview(1);assert.equal(h.state.activeReviewId,'b');assert.equal(h.calls.scrolls,0,'do not scroll using the preceding page viewport');pending.resolve(page());await first;for(const frame of h.frames)frame();assert.equal(h.calls.scrolls,1,'the newest anchor must be scrolled after the new page layout');assert.deepEqual(h.els.reviewOverlay.children.filter(c=>c.className.includes('is-active')).map(c=>c.dataset.reviewId),['b'])});
test('a newer viewport redraw preserves the pending review anchor without resurrecting manual selection',async()=>{for(const manual of [false,true]){const h=harness(),old=deferred(),newer=deferred();completePdf(h);let reads=0;h.state.pdfDoc.getPage=()=>++reads===1?old.promise:newer.promise;const first=h.context.focusReview('b');if(manual)await h.context.goToPage(2);const redraw=h.context.renderCurrentPage();newer.resolve(page());await redraw;old.resolve(page());await first;for(const frame of h.frames)frame();assert.equal(h.calls.scrolls,manual?0:1);assert.equal(h.state.activeReviewId,manual?'':'b')}});
test('delayed saved-session restoration cannot apply A notes or UI preferences to B',async()=>{const h=harness(),pending=deferred();h.context.idbGet=()=>pending.promise;const restoring=h.context.restoreSavedSession();await h.context.beginSourceChange();h.state.file={name:'B.pdf'};h.state.sessionKey='B';h.state.pdfDoc={};h.state.pageCount=3;h.state.reviews=[review('B-only',1)];pending.resolve({reviews:[review('A-restored',3)],ui:{currentPage:3,reviewFilterStatus:'resolved',reviewSort:'created'}});assert.equal(await restoring,false);assert.deepEqual(ids(h),['B-only']);assert.equal(h.state.currentPage,1);assert.equal(h.state.reviewFilterStatus,'all');assert.equal(h.state.reviewSort,'page')});
test('saved-session restoration still applies the current record and rejects a superseded session',async()=>{for(const replaced of [false,true]){const h=harness(),pending=deferred();h.context.idbGet=()=>pending.promise;const restoring=h.context.restoreSavedSession();if(replaced)h.context.applySessionRecord({reviews:[review('imported',2)]});pending.resolve({reviews:[review('saved',3)],ui:{currentPage:3}});assert.equal(await restoring,!replaced);assert.deepEqual(ids(h),[replaced?'imported':'saved']);assert.equal(h.state.currentPage,replaced?1:3)}});
